version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/ecommerce/AutoKart-Frontend

hooks:
  ApplicationStop:
    - location: scripts/stop_backend.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_backend.sh
      timeout: 300
      runas: root
