version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd AutoKart-Backend
      - npm install

  build:
    commands:
      - echo "Build step (Node app)"

artifacts:
  files:
    - '**/*'
